[project]
name = "orion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord>=2.3.2",
    "dynaconf>=3.2.6",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.8",
]
